### ISSUE TITLE
App crashes on some devices when clicking the donate button

### ISSUE THREAD

**Issue by vascYT** [VShopApp/mobile#24]
I cannot reproduce this myself, but I have seen a lot of reports on Discord (which is also confirmed by Firebase Crashlytics).

**Comment by vascYT** [comment]
I will probably start by updating the react native stripe sdk to the latest version.

**Comment by mkrnlox** [comment]
https://github.com/user-attachments/assets/3eb1bae0-e4c2-462e-bf63-9bc472a2a471

android 13

**Comment by mkrnlox** [comment]
here crash logs
[log_crash_am.log](https://github.com/user-attachments/files/17166112/log_crash_am.log)

**Comment by vascYT** [comment]
thanks, much appreciated!

**Comment by vascYT** [comment]
Good news, I was able to find the issue. It was a minor (but also major) oversight on my end, which happened when I was trying to release an update fixing the login as quickly as possible, so I accidentally forgot to include the publishable secret in the production build... This issue is now resolved with [v2.7.6](https://github.com/VShopApp/mobile/releases/tag/v2.7.6).
