### ISSUE TITLE
Skin Names

### ISSUE THREAD

**Issue by pixo2000** [VShopApp/mobile#33]
I set the Language to english, and everything except the skin Names got Set to english but i want the Names also to be english

**Comment by vascYT** [comment]
Hello,
thanks for the report. Which version do you currently have installed?

**Comment by vascYT** [comment]
I'm sorry but VShop is not available on the Google play store. Where exactly did you download it from?

**Comment by pixo2000** [comment]
My Bad, thought of another app with a similar Name. I use Version 3.1.0-beta.2. Download is from Github Releases

**Comment by vascYT** [comment]
Ah no worries, makes sense now. This bug is only in the beta version of the app, you can manually fix it for now by clearing the app cache. The fix for it will be shipped with the next update (commit: f53afffa253719cc1a7972df0db8968007e7e1d6) 👍

**Comment by vascYT** [comment]
Thanks again for your report. Wouldn't have been able to spot this issue without you 🙏
