### ISSUE TITLE
Account Switcher

### ISSUE THREAD

**Issue by Meff1u** [VShopApp/mobile#8]
Hi man, your application has no bugs or sth (at least I haven't found any). I just wanted to submit suggestionbut I didn't know where.  As you'd expect from the title, I'm writing oabout the ability to switch between accounts to check the store. If you don't have such plans, time or skills - no problem! It's just my "whim", I have several accounts and it would just be easier for me to switch between them than to log in every time. You are doing a good job!

**Comment by vascYT** [comment]
Hi Mefuuu! Sorry for the late reply. I will definitely consider your suggestion in the future. Thank you!

**Comment by vascYT** [comment]
I'm closing this since I won't be adding any new features to VShop anymore (see https://docs.vshop.one/distribution-update/).
