### ISSUE TITLE
Login into account with Cyrillic nickname.

### ISSUE THREAD

**Issue by hippy0** [VShopApp/mobile#9]
BUG:

After a change of nickname to "мерзавец" (nickname with Cyrillic alphabet letters), I get the bug with infinite loading page (message on the picture - username loading)

<details>
<summary>Screenshot</summary>

![изображение](https://github.com/VShopApp/mobile/assets/70841218/33391398-bfb8-4815-874c-9e1227ac3375)

</details>

I tried to reinstall the app, but it's doesn't work for me, before i changed my valorant nickname everything works fine.

**Comment by vascYT** [comment]
Hello,
this is a known issue with the iOS version of VShop from the App Store. You can get the fixed version from the [Testflight](https://testflight.apple.com/join/BeOIXqDR). Alternatively, you can wait until the update is publicly available.
